### ISSUE TITLE
Create neighbor matrix

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/bard-safecare-spatial-1#3]
@bard1536, please send me an example of converting spatial polygon boundaries into the type of neighbor matrix you want for the spatial analysis.

After that, I'll reassign the issue to me.

**Comment by wibeasley** [comment]
I need to leave in ~15 minutes.  If you send this to me now, I might be able to return it first.  Otherwise, I'll resume after the kids' bedtime.

**Comment by DavidBard** [comment]
ouch.  don't think i'll make that deadline.  i'll hurry.

**Comment by wibeasley** [comment]
Actually, don't try.  I was just told we need to wrap the present for the birthday party.

**Comment by DavidBard** [comment]
screening data uploaded.  realScreenDat.csv inside National/Data folder

**Comment by wibeasley** [comment]
@bard1536 What type of neighbor matrix do you need?  Can you please send me an example?  Either of the final product, or of the function that you've used before.

**Comment by wibeasley** [comment]
Note: David used the polygon object created by `maptools::map2SpatialPolygons`, and fed it through `spdep::poly2nb` and `spdep::nb2mat` to get the neighbor/adjacency matrix.
