### ISSUE TITLE
github for windows application "failed commit"

### ISSUE THREAD

**Issue by DavidBard** [OuhscBbmc/bard-safecare-spatial-1#7]
same issue (#51) submitted for  MIECHV/MReporting project.  outside contributor suggested:

git config --global user.name "Your Name"
git config --global user.email email@domain.com

this worked!
@wibeasley

**Comment by wibeasley** [comment]
@akhorolets. Thanks again for you help when you suggested this fix, on another GitHub repository of ours.  

(If you're wondering why that first repository is not visible anymore, a collaborating state agency requested that we make it private.)
